# Generated by Django 5.1.1 on 2024-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_product_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification', models.CharField(max_length=22)),
                ('name_product', models.CharField(max_length=22)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
